# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelMatrixSqrt <- function(x) {
    .Call('_RcppThread_parallelMatrixSqrt', PACKAGE = 'RcppThread', x)
}

parallelMatrixSqrt2 <- function(x) {
    .Call('_RcppThread_parallelMatrixSqrt2', PACKAGE = 'RcppThread', x)
}

sleep <- function(times) {
    invisible(.Call('_RcppThread_sleep', PACKAGE = 'RcppThread', times))
}

sleep2 <- function(times) {
    invisible(.Call('_RcppThread_sleep2', PACKAGE = 'RcppThread', times))
}

test <- function(x) {
    .Call('_RcppThread_test', PACKAGE = 'RcppThread', x)
}

